name: Release
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base-image:
          - "debian:10.8"
          - "ubuntu:20.04"
    steps:
      - uses: actions/checkout@v2
      - run: docker build --build-arg BASE_IMAGE=${{ matrix.base-image }} --tag=temp/${{ matrix.base-image }} .
      - run: mkdir -p output && docker run --rm -v $PWD/output:/mnt/output temp/${{ matrix.base-image }} sh -c "cp /work/*.deb /mnt/output/"
      - name: Rename
        run: cd output && (export prefix_name=$(echo "${{ matrix.base-image }}" | sed -e 's/:/_/g') && for name in $(ls *.deb); do mv "$name" "${{ matrix.base-image }}-$name"; done)
      - run: cd output && ls -al && sha256sum *.deb
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            output/*.deb

